# transmission
---
app_user: transm
app_uid: 1204
app_group: transm
app_gid: 1204

app_name: transmission
app_port: 9091
app_data_port: 51412

cpu_core_limit: 2
memory_limit: "512M"

app_media: "{{ transmission_path }}"

transmission_blocklist_enabled: 'false'
transmission_blocklist: ''
