# plex vars/main.yml
---
app_user: plex
app_uid: 1202
app_group: plex
app_gid: 1202

plex_server_dir: "config/Library/Application Support/Plex Media Server"
media_path: "/mnt/media"

app_port: 32500
app_name: plex

append_groups: "video,render,systemd-journal"

cpu_core_limit: 4
memory_limit: "6G"
